version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network
    

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app_network

  auth_db:
    image: mysql:8.0
    container_name: authDB
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_AUTH_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_AUTH_NAME}
      MYSQL_USER: ${DB_AUTH_USER}
      MYSQL_PASSWORD: ${DB_AUTH_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - app_network

  auth_web:
    build:
      context: ./auth_service/
      dockerfile: Dockerfile
    container_name: authService
    command: >
      sh -c "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver --noreload 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - auth_db
    networks:
      - app_network

  profiles_db:
    image: mysql:8.0
    container_name: profilesDB
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PROFILES_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_PROFILES_NAME}
      MYSQL_USER: ${DB_PROFILES_USER}
      MYSQL_PASSWORD: ${DB_PROFILES_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - profiles_db_data:/var/lib/mysql
    networks:
      - app_network

  profiles_web:
    build:
      context: ./profiles_service/
      dockerfile: Dockerfile
    container_name: profilesService
    command: >
      sh -c "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver --noreload 0.0.0.0:8000"
    ports:
      - "8002:8000"
    volumes:
      - profiles_media_volume:/app/media
    depends_on:
      - profiles_db
    networks:
      - app_network

  profiles_web_kafka_listener:
    build:
      context: ./profiles_service/
      dockerfile: Dockerfile
    container_name: profilesServiceKafkaListener
    command: >
      sh -c "python start_kafka_consumer.py"
    ports:
      - "8022:8000"
    depends_on:
      - profiles_db
    networks:
      - app_network

  hotels_db:
    image: mysql:8.0
    container_name: hotelsDB
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_HOTELS_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_HOTELS_NAME}
      MYSQL_USER: ${DB_HOTELS_USER}
      MYSQL_PASSWORD: ${DB_HOTELS_PASSWORD}
    ports:
      - "3312:3306"
    volumes:
      - hotels_db_data:/var/lib/mysql
    networks:
      - app_network

  hotels_web:
    build:
      context: ./hotels_service/
      dockerfile: Dockerfile
    container_name: hotelsService
    command: >
      sh -c "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver --noreload 0.0.0.0:8000"
    ports:
      - "8003:8000"
    volumes:
      - hotels_media_volume:/app/media
    depends_on:
      - hotels_db
    networks:
      - app_network

  bookings_db:
    image: mysql:8.0
    container_name: bookingsDB
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_BOOKINGS_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_BOOKINGS_NAME}
      MYSQL_USER: ${DB_BOOKINGS_USER}
      MYSQL_PASSWORD: ${DB_BOOKINGS_PASSWORD}
    ports:
      - "3313:3306"
    volumes:
      - bookings_db_data:/var/lib/mysql
    networks:
      - app_network

  bookings_web:
    build:
      context: ./bookings_service/
      dockerfile: Dockerfile
    container_name: bookingsService
    command: >
      sh -c "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver --noreload 0.0.0.0:8000"
    ports:
      - "8004:8000"
    depends_on:
      - bookings_db
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redisCache
    ports:
      - "6379:6379"
    networks:
      - app_network

  react_frontend:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
    container_name: reactFrontend
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  auth_db_data:
    driver: local
  profiles_db_data:
    driver: local
  hotels_db_data:
    driver: local
  bookings_db_data:
    driver: local
  profiles_media_volume:
  hotels_media_volume:

networks:
  app_network:
    driver: bridge