version: '3.8'

services:
  auth_db:
    image: mysql:8.0
    container_name: auth_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - auth_network

  auth_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    command: >
      sh -c "python manage.py makemigrations && \
      python manage.py migrate && \
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - auth_db
    networks:
      - auth_network

volumes:
  auth_db_data:
    driver: local

networks:
  auth_network:
    driver: bridge
