# Generated by Django 5.1.3 on 2024-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='owner_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
