# Generated by Django 5.1.3 on 2024-11-27 11:37

import django.db.models.deletion
import hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.preview_image_upload_path),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=hotels.models.images_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
        ),
    ]
