# Generated by Django 5.1.3 on 2024-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_preview_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_bookings',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
