# Generated by Django 5.1.3 on 2024-11-23 09:21

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_picture_upload_path),
        ),
    ]
