# Generated by Django 5.1.3 on 2024-12-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_bookings',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
